### ISSUE TITLE
cosocket disabled in the context of log_by _lua*

### ISSUE THREAD

**Issue by flisky** [cloudflare/lua-resty-logger-socket#21]
OpenResty 1.11.2.1.

According to current docs, the cosocket API is disabled in the log_by_lua context.

I need log some variables like `ngx.var.status`, and which context should I put it into? Thanks!

**Comment by agentzh** [comment]
This library uses log_by_lua* + ngx.timer.at to do cosocket in the log phase, so it should work out of the box with OpenResty 1.11.2.1 and any other versions of OpenResty.

**Comment by agentzh** [comment]
ngx.var works in every request phases. Read the manual.

**Comment by flisky** [comment]
Ok, I found the problem. I called `logger.flush()` directly, which is really flushing.
And the flushing logic should be called by `ngx.timer.at` in the `log_by_lua` block.

A document update may be helpful.

ngx.var.status is empty before `log_by_lua`, so I need it in the certain context.

**Comment by agentzh** [comment]
@flisky `ngx.var.status` is the HTTP response status code. It's surely empty in earlier phases where the HTTP response header is not even generated! It has meaningful value as early as the header filter phase.

**Comment by flisky** [comment]
Got it, and thanks for the information.
