### ISSUE TITLE
Option to NOT concatenate log_buffer_data into single message?

### ISSUE THREAD

**Issue by geemang2000** [cloudflare/lua-resty-logger-socket#23]
First off, awesome library.

I'm using Syslog-ng to collect messages from lua.  I need each log message to be uniquely processed by Syslog.   resty-logger concat's the contents of log_buffer_data into a single message unless I explicitly flush() after each log statement.

Is there any value (performance / function) to send spooled msg's (w/o concatenation) as unique msg's after timeout or the number msgs in log_buffer_data is > than a certain size?

Seems, there is a lock hit every time flush is called.

**Comment by agentzh** [comment]
@geemang2000 Sending each individual message separately leads to far more number of syscalls, which is much more expensive and will impact your server's performance a lot. You should use newlines or etc way to logically separate your messages in a bulk.

**Comment by geemang2000** [comment]
Understood, so the idea is to send the msg formatted (adding timestamp etc) to your liking appended with \n and dumb down Syslog-NG formatting?

Kinda off topic, but if Syslog-NG can turn multi-line messages into unique log statements this might work well.

**Comment by agentzh** [comment]
@geemang2000 Frankly, we usually do not use syslog-ng as the receiving side. Some of our enterprise users use ngx_stream_lua_module to create TCP servers to receive messages.

**Comment by geemang2000** [comment]
Thanks! truly appreciate your feedback.
