### ISSUE TITLE
Use "--- grep_error_log" and "--- grep_error_log_out" in the test suite

### ISSUE THREAD

**Issue by agentzh** [cloudflare/lua-resty-logger-socket#3]
Right now the test suite uses the "--- ordered_error_log" section in the section, which has been rejected in the corresponding ticket for Test::Nginx:

https://github.com/agentzh/test-nginx/pull/6

Now that we have "--- grep_error_log" and "-- grep_error_log_out" in Test::Nginx, we should make use of them in the test suite.

**Comment by stml2013** [comment]
when I lean to use **grep_log_error**  ,
` 79 === TEST 4: grep_log_error
 80 --- http_config eval: $::HttpConfig
 81 --- config
 82     location /test {
 83         content_by_lua '
 84             print("it is matched!")
 85             print("it is matched!")
 86             print("it is matched!")
 87         ';
 88     }
 89 
 90 --- request
 91 GET /test
 92 --- grep_error_log
 93 it is matched!
 94 --- grep_error_log_out
 95 it is matched!
 96 it is matched!
 97 it is matched!
`
 I get some error:
#   Failed test 'TEST 4: grep_log_error - grep_error_log_out (req 0)'
#   at /usr/home/yupei1/local/perl-5.24.0/lib/site_perl/5.24.0/Test/Nginx/Socket.pm line 1052.
#          got: ""
#       length: 0
#     expected: "it is matched!\x{0a}it is matched!\x{0a}it is matched!\x{0a}"
#       length: 45
#     strings begin to differ at char 1 (line 1 column 1)
I did not why？
