### ISSUE TITLE
what's the best effective way to collect log in nginx lua 

### ISSUE THREAD

**Issue by JoyChou93** [cloudflare/lua-resty-logger-socket#33]
we can use 
- ngx.log
- iopen
- socket

so, which one or other way is the best ?

**Comment by calio** [comment]
`ngx.log` is fine, it's the standard way of logging. Do not use `iopen` to write files from Lua code as it will block current Nginx worker process and cause performance issue. `socket` is also good if you have a service that collects logs remotely. Otherwise, just use `ngx.log`.

**Comment by JoyChou93** [comment]
@calio But `ngx.log` has a limit of 2048 bytes.

**Comment by calio** [comment]
@JoyChou93 no matter which way to choose, there is always some kind of limit. If you know 2048 bytes limit is a problem, then switch to other ways.
