### ISSUE TITLE
Would u develop lua-resty-logger as lib writes logs into local files

### ISSUE THREAD

**Issue by hongxiaolong** [cloudflare/lua-resty-logger-socket#39]
as follows:

```
-- log file

local logger_0 = new logger("PATH")

logger_0.debug("debug"); --for debug

logger_0.info("info"); --for info

logger_0.error("error"); --for error

-- another log file

local logger_1 = new logger("PATH")

logger_1.debug("debug"); --for debug

logger_1.info("info"); --for info

logger_1.error("error"); --for error
```

thks

**Comment by jdesgats** [comment]
As the name implies, `lua-resty-logger-socket` is targeted as the specific use case of logging over the network.

Local files are tricky in nginx as writing to them uses blocking syscalls, for logging purposes it is usually fine if your storage is fast and writes are buffered (this is what `ngx.log` dos already).

It for some reason `ngx.log` is not enough for your use case, and you are aware of limitation of filesystem writes, you might be interested in some of the existing Lua logging libraries: https://luarocks.org/search?q=log
