### ISSUE TITLE
whats wrong with logging in content_by_lua?

### ISSUE THREAD

**Issue by owenliang** [cloudflare/lua-resty-logger-socket#44]
Somebody said that buffered log wont be flush in content_by_lua before it is full, but can be flushed in log_by_lua, What is the difference between them?

**Comment by agentzh** [comment]
@owenliang No such difference exists at all.

**Comment by agentzh** [comment]
@owenliang nginx's access log buffering is completely controlled by the `buffer` parameter of nginx's `access_log` directive:

http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log
